name: cmake-build
on: [push]
jobs:
  linux-build:
    strategy:
      matrix:
        image: ['conanio/gcc11-ubuntu16.04:1.39.0', 'conanio/clang12-ubuntu16.04:1.39.0']
        libcxx: [libstdc++11, libc++]
        shared: [shared, static]
        exclude:
          - image: 'conanio/gcc11-ubuntu16.04:1.39.0'
            libcxx: libc++
        include:
          - image: 'conanio/gcc11-ubuntu16.04:1.39.0'
            profile: gcc11
          - image: 'conanio/clang12-ubuntu16.04:1.39.0'
            libcxx: libc++
            profile: clang12-libc++
          - image: 'conanio/clang12-ubuntu16.04:1.39.0'
            libcxx: libstdc++11
            profile: clang12-libstdc++

    runs-on: ubuntu-20.04
    container:
      image: ${{ matrix.image }}
      options: '--user=root'
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          bash .github/workflows/set_env_vars.sh \
            ${{ matrix.shared }}
      - name: Create conan cache keys
        run: |
          CONAN_ARGS="
            --profile .github/workflows/conan/profiles/${{ matrix.profile }} \
            -o shared=${SAMPLE_SHARED} \
            --build missing
          "
          conan lock create conanfile.py ${CONAN_ARGS} --base --lockfile-out base.lock
          conan lock create conanfile.py ${CONAN_ARGS}
      - name: Get conan cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.conan/data
            !~/.conan/data/**/conan_sources.tgz
          key: conan-${{ matrix.profile }}-${{ hashfiles('base.lock') }}-${{ hashFiles('conan.lock') }}
          restore-keys: |
              conan-${{ matrix.profile }}-${{ hashfiles('base.lock') }}
              conan-${{ matrix.profile }}
      - name: Install conan dependencies
        run: |
          conan install . \
            --install-folder build \
            --lockfile conan.lock \
            --build missing
      - name: build with cmake
        run: |
          conan build . --build-folder build
      - name: Run tests
        run: |
          cd build
          ctest --extra-verbose
  windows-build:
    strategy:
      matrix:
        shared: [shared, static]
        profile: [vs2019, vs2019-clang]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          bash .github/workflows/set_env_vars.sh \
            ${{ matrix.shared }}
        shell: bash
      - name: Create conan cache keys
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade conan
          CONAN_ARGS="
            --profile .github/workflows/conan/profiles/${{ matrix.profile }} \
            -o shared=${SAMPLE_SHARED} \
            --build missing
          "
          conan lock create conanfile.py ${CONAN_ARGS} --base --lockfile-out base.lock
          conan lock create conanfile.py ${CONAN_ARGS}
        shell: bash
      - name: Get conan cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.conan/data
            !~/.conan/data/**/conan_sources.tgz
          key: conan-${{ matrix.profile }}-${{ hashfiles('base.lock') }}-${{ hashFiles('conan.lock') }}
          restore-keys: |
            conan-${{ matrix.profile }}-${{ hashfiles('base.lock') }}
            conan-${{ matrix.profile }}
      - name: Install conan dependencies
        run: |
          conan install . \
            --install-folder build \
            --lockfile conan.lock \
            --build missing
        shell: bash
      - name: build with cmake
        run: |
          conan build . --build-folder build
        shell: bash
      - name: Run tests
        run: |
          cd build
          ctest --extra-verbose
        shell: bash
  mac-build:
    strategy:
      matrix:
        shared: [shared, static]
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Set environment variables
        run: |
          bash .github/workflows/set_env_vars.sh \
            ${{ matrix.shared }}
          echo "CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV
      - name: Create conan cache keys
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade conan
          CONAN_ARGS="
            --profile .github/workflows/conan/profiles/apple-clang12 \
            -o shared=${SAMPLE_SHARED} \
            --build missing
          "
          conan lock create conanfile.py ${CONAN_ARGS} --base --lockfile-out base.lock
          conan lock create conanfile.py ${CONAN_ARGS}
      - name: Get conan cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.conan/data
            !~/.conan/data/**/conan_sources.tgz
          key: conan-${{ matrix.profile }}-${{ hashfiles('base.lock') }}-${{ hashFiles('conan.lock') }}
          restore-keys: |
            conan-${{ matrix.profile }}-${{ hashfiles('base.lock') }}
            conan-${{ matrix.profile }}
      - name: Install conan dependencies
        run: |
          conan install . \
            --install-folder build \
            --lockfile conan.lock \
            --build missing \
            --generator virtualrunenv
      - name: build with cmake
        run: |
          conan build . --build-folder build
      - name: Run tests
        run: |
          cd build
          source activate_run.sh
          ctest --extra-verbose
