name: cmake-build
on: [push]
jobs:
  linux-build:
    strategy:
      matrix:
        image: ['conanio/gcc11-ubuntu16.04:1.39.0', 'conanio/clang12-ubuntu16.04:1.39.0']
        libcxx: [libstdc++11, libc++]
        shared: [shared, static]
        exclude:
          - image: 'conanio/gcc11-ubuntu16.04:1.39.0'
            libcxx: libc++
        include:
          - image: 'conanio/gcc11-ubuntu16.04:1.39.0'
            profile: gcc11
          - image: 'conanio/clang12-ubuntu16.04:1.39.0'
            libcxx: libc++
            profile: clang12-libc++
          - image: 'conanio/clang12-ubuntu16.04:1.39.0'
            libcxx: libstdc++11
            profile: clang12-libstdc++

    runs-on: ubuntu-20.04
    container:
      image: ${{ matrix.image }}
      options: '--user=root'
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          bash .github/workflows/set_env_vars.sh \
            ${{ matrix.shared }}
      - name: Install conan dependencies
        run: |
          conan install . \
            --profile .github/workflows/conan/profiles/${{ matrix.profile }} \
            --install-folder build \
            -o shared=${SAMPLE_SHARED} \
            --build missing
      - name: build with cmake
        run: |
          conan build . --build-folder build
      - name: run tests
        run: |
          cd build
          ctest --extra-verbose
  windows-build:
    strategy:
      matrix:
        shared: [shared, static]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          bash .github/workflows/set_env_vars.sh \
            ${{ matrix.shared }}
        shell: bash
      - name: Install and configure conan
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade conan
          conan install . \
            --profile .github/workflows/conan/profiles/vs2019 \
            --install-folder build \
            -o shared=${SAMPLE_SHARED} \
            --build missing
        shell: bash
      - name: build with cmake
        run: |
          conan build . --build-folder build
        shell: bash
      - name: run tests
        run: |
          cd build
          ctest --extra-verbose
        shell: bash
  mac-build:
    strategy:
      matrix:
        shared: [shared, static]
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Set environment variables
        run: |
          bash .github/workflows/set_env_vars.sh \
            ${{ matrix.shared }}
          echo "CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV
      - name: Install and configure conan
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade conan
          conan install . \
            --profile .github/workflows/conan/profiles/apple-clang12 \
            --install-folder build \
            -o shared=${SAMPLE_SHARED} \
            --build missing
      - name: build with cmake
        run: |
          conan build . --build-folder build
      - name: run tests
        run: |
          cd build
          ctest --extra-verbose
