name: Diagnostics
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  diagnostics:
    runs-on: ubuntu-24.04

    env:
      CONAN_HOME: "${{ github.workspace }}/conan"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install conan and config
        run: |
          pip install --upgrade \
            GitPython \
            conan \
            ninja
          conan profile detect
          conan config install .github/workflows/conan

      - name: configure with cmake
        run: |
          cmake --preset diagnostics \
            -D CMAKE_C_COMPILER=$(realpath $(which clang)) \
            -D CMAKE_CXX_COMPILER=$(realpath $(which clang))++

      - name: Setup conan cache
        uses: actions/cache@v4
        with:
          key: diagnostics
          path: ${{ env.CONAN_HOME }}/p
          save-always: true

      - name: run clang-tidy
        run: |  
          TARGET="origin/main"
          if [[ -n "$GITHUB_BASE_REF" ]]; then
            TARGET="origin/$GITHUB_BASE_REF"
          fi
          CHANGES=$(python scripts/changed_files.py build/diagnostics/compile_commands.json --target=${TARGET})
          if [[ -z "${CHANGES}" ]]; then
            echo "::notice ::No changes for static analysis"
            exit 0
          fi
          
          clang-tidy \
            -p build/diagnostics \
            --header-filter='.*' \
            --warnings-as-errors='*' \
            ${CHANGES}

      - name: clean conan cache
        run: |
          conan cache clean "*" --temp
        if: always()
